@beverage_order_system_HostAddress = http://localhost:5234
@access_token = x-access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIwMTllNTVmYS1jYmI5LTdmM2MtYWZiYi00YmY5YmQzOTM0NzgiLCJVc2VybmFtZSI6Im5ndXllbiBkb2UxIiwiZXhwIjoxNzc5OTAxMzY4fQ.8kxG6O3d1kGdol-JOv9-8pjD_SnTq8gi9fla9oz_Hl4
@refresh_token = 

GET {{beverage_order_system_HostAddress}}/weatherforecast/
Accept: application/json

### Get Menu Item

GET {{beverage_order_system_HostAddress}}/api/v1/menu?pageindex=1&pagesize=100
Accept: application/json

### Add Menu Item
POST {{beverage_order_system_HostAddress}}/api/v1/menu/new-item
Accept: application/json
Content-Type: application/json
Cookie: {{access_token}}

{
    "name": "milk coffee",
    "categoryid": 2,
    "baseprice": 100000,
    "isavailable": true    
}

### User Register
POST {{beverage_order_system_HostAddress}}/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "username": "nguyen doe1",
    "password": "testing1"
}

### User Login
POST {{beverage_order_system_HostAddress}}/api/v1/auth/login
Content-Type: application/json

{
    "username": "nguyen doe1",
    "password": "testing1"
}

### Refresh Token
POST {{beverage_order_system_HostAddress}}/api/v1/auth/refresh
Accept: application/json
Cookie: x-refresh-token=ufVm1tnT6ze8YrpFR%2F%2FMiLGdCbXzjd49bUzVuOhrt3nCkMllRPhO5gNzJOnQRgRdXYRwWmDLRehMsWG7eukDGg%3D%3D

{}

### Update Product
PATCH {{beverage_order_system_HostAddress}}/api/v1/menu/1/item-update
Accept: application/json
Content-Type: application/json
Cookie: {{access_token}}

{
    "name": "mi",
    "categoryid": 4,
    "baseprice": 100000,
    "isavailable": false
}

### Delete Product
DELETE {{beverage_order_system_HostAddress}}/api/v1/menu/3/delete
Cookie: {{access_token}}

### Create Order
POST {{beverage_order_system_HostAddress}}/api/v1/order/new-order
Accept: application/json
Content-Type: application/json

{
    
}

###Get Order
GET {{beverage_order_system_HostAddress}}/api/v1/order/019e98c5-cf46-7244-8aeb-6aadaf92779d/get-item
Accept: application/json


### Add Item
POST {{beverage_order_system_HostAddress}}/api/v1/order/019e98c5-cf46-7244-8aeb-6aadaf92779d/new-order-item
Accept: application/json
Content-Type: application/json

{
    "productid": 1
}