<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>beverage_order_system</RootNamespace>
    <UserSecretsId>08f00dd0-2dbc-4808-9462-02d0df3a5c32</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="10.0.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DbConfig\" />
    <Folder Include="Dto\" />
    <Folder Include="Exception\" />
    <Folder Include="Exception\AuthException\" />
    <Folder Include="Exception\UserException\" />
    <Folder Include="Feature\Auth\" />
    <Folder Include="Feature\Auth\RefreshToken\" />
    <Folder Include="Feature\Auth\UserLogin\" />
    <Folder Include="Feature\Auth\UserRegister\" />
    <Folder Include="Feature\Menu\AddMenuItem\" />
    <Folder Include="Infrastructure\" />
    <Folder Include="Model\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="beverage-order-system.Test\**" />
    <Content Remove="beverage-order-system.Test\**" />
    <EmbeddedResource Remove="beverage-order-system.Test\**" />
    <None Remove="beverage-order-system.Test\**" />
  </ItemGroup>

</Project>
