@beverage_order_system_HostAddress = http://localhost:5234

GET {{beverage_order_system_HostAddress}}/weatherforecast/
Accept: application/json

### Get Menu Item

GET {{beverage_order_system_HostAddress}}/api/v1/menu?pageindex=100&pagesize=100
Accept: application/json